### ISSUE TITLE
Issue with running CLI with Gitlab CI

### ISSUE THREAD

**Issue by cormacrw** [UiPath-Services/UiPath-DevOps-Scripts#6]
I am trying to run the UIPath CLI in the gitlab cli, here is what is in my yml.

```
  before_script:
    - New-Item -Path ".\\" -ItemType "directory" -Name "scripts"
    - Invoke-WebRequest "https://github.com/UiPath-Services/UiPath-DevOps-Scripts/raw/main/scripts/UiPathRunTest.ps1" -OutFile ".\scripts\UiPathRunTest.ps1"
  script:
    - .\scripts\UiPathRunTest.ps1 -orchestrator_url "https://cloud.uipath.com" -orchestrator_tenant ${UIPATH_TENANT_NAME} -applicationId ${UIPATH_APPLICATION_ID} -applicationSecret ${UIPATH_APPLICATION_SECRET} -accountForApp ${UIPATH_ACCOUNT_NAME} -project_path ".\test\project.json" -environment ${UIPATH_FOLDER} -out junit -applicationScope "OR.Monitoring OR.Folders OR.BackgroundTasks OR.TestSets OR.TestSetExecutions OR.TestSetSchedules OR.Settings OR.Robots OR.Machines OR.Execution OR.Assets OR.Users OR.Jobs"
  artifacts:
    when: always
    paths:
      - ./junitresult.xml
    reports:
      junit: ./junitresult.xml
  tags:
    - windows
```

however I get the following error,
![image](https://user-images.githubusercontent.com/32876806/219472044-80017206-955f-492c-b881-4e180c9e2325.png)

I have tried to install dotnet seperately but it still doesn't seem to work, the readme of this repo suggests that the scripts will download all dependencies, and in the gitlab ci example provided there is no where dotnet is installed.

What am I doing wrong?

Thanks in advance.
